---
# tasks file for etcd-ansible-operator
- block:
    - name: Set status when cluster is available
      vars:
        etcd_status: Unknown
        control_paused: true
        version: ""
        etcd_cluster_members: []
        etcd_cluster_member_names: []
        size: ""
      k8s_status:
        api_version: etcd.database.coreos.com/v1beta2
        kind: EtcdCluster
        name: "{{ etcd_cluster_name }}"
        namespace: "{{ etcd_namespace }}"
        status: "{{ lookup('template', 'status.yaml') | from_yaml }}"


    - name: "end play if nothing spec.pause is true"
      debug:
        msg: "skipping reconciliation"

    - meta: end_play

  when: pause is defined and pause == true

- name: Call backup task if it is for backup
  include_tasks: backup_s3.yaml
  when: backup_s3 is defined

- name: Determine if secure client
  set_fact:
    etcd_secure_client: "present"
  when: (_tls is not undefined and _tls.static is not undefined and _tls.static.operator_secret is not undefined
                                    and _tls.static.operator_secret|length > 0 )

- name: Determine if secure peer
  set_fact:
    etcd_secure_peer: "present"
  when: ( _tls is not undefined and _tls.static is not undefined and _tls.static.member is not undefined
        and _tls.static.member.peer_secret|length > 0)


- name: call create certs on secure client
  include_tasks: create_certs.yaml
  when: etcd_secure_client == "present"

- name: create services if it does not exist
  include_tasks: create_services.yml
  when: (etcd_cluster_services|length==0)

- name: reconcile pods
  include_tasks: reconcile_pods.yaml
