---
#this task maintains members for a cluster and other commands.
- name: set etcd_cluster_phase
  set_fact:
    etcd_cluster_phase: "existing"
  when: etcd_stateful_set|length > 0

- name: get members of cluster
  vars:
    members: "{{ q('etcd_member', cluster_host= etcd_cluster_name + '-client.' + etcd_namespace + '.svc',
                  cluster_port= etcd_client_port) }}"
  set_fact:
    etcd_cluster_members: "{{ members }}"
  when: (etcd_cluster_phase == "existing" and etcd_secure_client == "absent")

- name: get members of cluster when secure client
  vars:
    members: "{{ lookup('etcd_member', cluster_host= etcd_cluster_name + '-client.' + etcd_namespace + '.svc',
                  cluster_port=etcd_client_port,
                  ca_cert=tls_directory + '/etcd-ca.cert',
                  cert_cert=tls_directory + '/etcd-client.crt',
                  cert_key=tls_directory + '/etcd-client.key') }}"
  set_fact:
    etcd_cluster_members: "{{ members }}"
  when: (etcd_cluster_phase == "existing" and etcd_secure_client == "present")

- name: set the "{{ etcd_cluster_name }}" resources state=present
  k8s:
    state: "present"
    definition: "{{ lookup('template', 'ss.yaml' | from_yaml ) }}"
  when: etcd_cluster_phase == "new"

- name: make sure all the pods are running
  k8s_facts:
    kind: StatefulSet
    api_version: apps/v1
    namespace: "{{ etcd_namespace }}"
    name: "{{ etcd_cluster_name }}"
  register: sts
  until: sts.get("resources", []) and sts.resources[0].get("status", {}).get("readyReplicas", 0) == {{ size }}
  retries: 30
  delay: 10

- name: set new size
  set_fact:
    etcd_stateful_set: "{{ lookup('template', 'ss.yaml' | from_yaml) }}"
  when: etcd_cluster_phase == "existing"

- name: patch the "{{ etcd_cluster_name }}" resources
  k8s:
    state: "present"
    definition: "{{ etcd_stateful_set }}"
  when: etcd_cluster_phase == "existing"

- name: remove members from cluster when scaling down
  vars:
    etcd_member_size: "{{ etcd_cluster_members|length|int }}"
  when: etcd_cluster_phase == "existing" and etcd_member_size|int > size
  include_tasks: remove_member.yaml